### ISSUE TITLE
Gruvbox missing.

### ISSUE THREAD

**Issue by DwordPtr** [vim-airline/vim-airline-themes#178]
I intend on adding this color scheme in here when I get a free minute. Just adding this issue to make the PR against.

**Comment by chrisbra** [comment]
see #145, #137 #105 and #121 and answer the related questions first.

**Comment by travisboss** [comment]
To maybe continue this morhetz has not updated or maintained gruvbox for quite some time now.  There are other versions of gruvbox for vim I would argue look better and are smaller, one does not even require a shell script for 256 color.  Would be great to move the theme to airline themes so other versions can be used and not need to install his version and use his theme only.

**Comment by chrisbra** [comment]
If that is the case, I am fine with including the gruvbox theme here.

**Comment by DwordPtr** [comment]
Sorry for the late reply. Unexpected stuff came up. Apparently there's a community gruvbox theme that supports ALOT of plugins github.com/gruvbox-community/gruvbox

**Comment by chrisbra** [comment]
it does have an airline theme file. so not sure we should add it here ping @rbong

**Comment by rbong** [comment]
Gruvbox is a bit more complicated than most themes. It comes with a lot of options that alter its highlight groups, making it impractical to move the airline theme here entirely without removing those options or relying on highlight groups created by gruvbox here.

Also please note that the community edition is just a fork of the original Gruvbox, if the original is too bloated so is the fork... No major overhauls have yet been made. So if that is a deciding factor in adopting a gruvbox alternative, I would suggest going ahead with that. However, it is currently maintained and open to contributors, so it has that going for it.

If you do adopt a different version of gruvbox without a builtin theme, I would ask that you please not take the "gruvbox" theme name so the airline theme within the plugin continues to be automatically loaded. I am guessing morhetz would appreciate not taking that name as well since he has not officially shut down the project, although I am not affiliated with him.

I will keep an eye on this discussion.

**Comment by ronald2wing** [comment]
Maybe you will want to make a gruvbox base16 colorscheme?
https://github.com/vim-airline/vim-airline-themes/issues/167

**Comment by chrisbra** [comment]
> Maybe you will want to make a gruvbox base16 colorscheme?

It's an open source project that lives from contributing, so sure, go ahead and create a PR.

**Comment by ronald2wing** [comment]
> > Maybe you will want to make a gruvbox base16 colorscheme?
> 
> It's an open source project that lives from contributing, so sure, go ahead and create a PR.

Right, thanks you for the encouragement. Working on it now.
